### ISSUE TITLE
Whitespace in string name

### ISSUE THREAD

**Issue by cleveHEX** [vcmi-mods/czech-translation#1]
I was playing the game with Czech language. I noticed a few typos, so I decided I will try to fix them, this repository is probably the one I was searching for. However, I have following question: I translated a dozen of projects already, but never saw a whitespace in string name, is this intended or should be removed?

![obrazek](https://github.com/vcmi-mods/czech-translation/assets/9021297/4ec71892-b137-45b1-89da-df89bae3e020)
Game.json L5984.

If it is a bug, I will fix it in my upcoming PR.

**Comment by cleveHEX** [comment]
Also to not open another issue, where can I find this to translate? I can't locate it in json files.
![obrazek](https://github.com/vcmi-mods/czech-translation/assets/9021297/36b8ba2f-b00c-497c-b5c1-0937480fbd75)
![obrazek](https://github.com/vcmi-mods/czech-translation/assets/9021297/0bf43edc-55c1-4337-b86a-1376452551dd)

**Comment by heroesiiifan** [comment]
@cewbdex No its not really a bug. It seems to come from the game itself. Nothing that have to fixed here.

Yes, there are a few more files to translated (this repo is only for files that cannot licensed under GPL).

Feel free to complete the Czech translation.

Copy, rename and edit these files and make a PR to vcmi
- https://github.com/vcmi/vcmi/blob/develop/Mods/vcmi/config/vcmi/english.json
- https://github.com/vcmi/vcmi/blob/develop/launcher/translation/english.ts
- https://github.com/vcmi/vcmi/blob/develop/mapeditor/translation/english.ts
