### ISSUE TITLE
Some strings are Polish

### ISSUE THREAD

**Issue by cleveHEX** [vcmi-mods/czech-translation#3]
In `game.json`, lines 1659-1802 (`core.bonus.*`) are Polish. Would be good if someone replaces them with English, as Czechs are more likely to understand English than Polish.

**Comment by heroesiiifan** [comment]
Was a mistake by me. Bonus have to be here: https://github.com/vcmi/vcmi/blob/develop/Mods/vcmi/config/vcmi/english.json

(already merged your PR to avoid conflicts, feel free to open a new one)
