### ISSUE TITLE
%s not replaced in-game

### ISSUE THREAD

**Issue by cleveHEX** [vcmi-mods/czech-translation#5]
![obrazek](https://github.com/vcmi-mods/czech-translation/assets/9021297/2b9fe307-4718-4d30-989a-03f75c466e76)
It's `core.genrltxt.7` in `game.json`. Not sure how to fix, where can be found the English translation to compare?

**Comment by IvanSavenko** [comment]
Bug in vcmi, will be fixed in 1.3.2 release

**Comment by cleveHEX** [comment]
Fedora did not ship 1.3.2 yet, but I guess we can close this?
